version: "3.7"
services:
  traefik:
    secrets:
      - traefik_users
  backend:
    secrets:
      - DJANGO_SECRETS
      - SOCIAL_PROVIDER_SECRETS
  frontend:
    secrets:
      - SOCIAL_PROVIDER_SECRETS
  celery_worker:
    secrets:
      - DJANGO_SECRETS
      - SOCIAL_PROVIDER_SECRETS

secrets:
  traefik_users:
    file: ../traefik_users
  DJANGO_SECRETS:
    file: ../django.secrets
  SOCIAL_PROVIDER_SECRETS:
    file: ../social-provider.secrets
