version: "3.7"
services:
  traefik:
    secrets:
      - prometheus_users
  prometheus:
    secrets:
      - prometheus_users
  grafana:
    secrets:
      - grafana_password

secrets:
  grafana_password:
    file: ../grafana_password
  prometheus_users:
    file: ../prometheus_users
