version: "3.7"
services:
  backend:
    environment:
      - FRONTEND_URL=http://localhost:3000
      - DEBUG=True
  frontend:
    environment:
      - API_URL=http://backend:8000
      - API_URL_BROWSER=http://localhost:8000
  celery_worker:
    environment:
      - DEBUG=True
