version: "3.7"
services:
  redis-exporter:
    image: oliver006/redis_exporter
  exporter:
    image: prom/node-exporter:latest
  prometheus:
    image: localhost/prometheus:latest
  grafana:
    image: localhost/grafana:latest
  portainer:
    image: portainer/portainer:latest
