version: "3.7"
services:
  backend:
    environment:
      - DEBUG=False
      - USE_SSL=True
      - FRONTEND_URL=https://${DOMAIN}
      - SECRETS_PATH=/run/secrets
  frontend:
    environment:
      - API_URL=http://backend:8000
      - API_URL_BROWSER=https://api.${DOMAIN}
      - SECRETS_PATH=/run/secrets
  celery_worker:
    environment:
      - DEBUG=False
      - SECRETS_PATH=/run/secrets
