version: '3.7'
services:
  backend:
    networks:
      - default
      - proxy
  grafana:
    networks:
      - default
      - proxy
  portainer:
    networks:
      - default
      - proxy
  proxy:
    networks:
      - default
      - proxy
  celery_worker:
    networks:
      - default
  postgres:
    networks:
      - default
  redis:
    networks:
      - default
  redis-exporter:
    networks:
      - default
  exporter:
    networks:
      - default
  prometheus:
    networks:
      - default

networks:
  default:
  proxy:
    external: true
