version: "3.7"
services:
  backend:
    environment:
      - DEBUG=False
      - USE_SSL=True
      - FRONTEND_URL=https://${DOMAIN}
  frontend:
    environment:
      - API_URL=http://backend:8000
      - API_URL_BROWSER=https://api.${DOMAIN}
  celery_worker:
    environment:
      - DEBUG=False
