version: "3.7"
services:
  backend:
    environment:
      - FRONTEND_URL=http://localhost
      - DEBUG=True
      - SECRETS_PATH=/
  frontend:
    environment:
      - API_URL=http://backend:8000
      - API_URL_BROWSER=http://api.localhost
      - SECRETS_PATH=/
  celery_worker:
    environment:
      - DEBUG=True
      - SECRETS_PATH=/
