version: '3.7'
services:
  backend:
    build:
      context: ../backend
      args:
        env: dev
  frontend:
    build:
      context: ../frontend
      args:
        env: dev
  celery_worker:
    build:
      context: ../backend
      dockerfile: worker.dockerfile
      args:
        env: dev
