version: "3.7"
services:
  postgres:
    env_file:
      - ../env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  backend:
    env_file:
      - ../env-postgres.env
      - ../env-backend.env
      - ../env-secret.env
    environment:
      - SERVER_HOST=${DOMAIN-localhost}
  frontend:
    env_file:
      - ../env-secret.env
  celery_worker:
    env_file:
      - ../env-postgres.env
      - ../env-backend.env
      - ../env-secret.env
    environment:
      - SERVER_HOST=${DOMAIN-localhost}
