version: "3.7"
services:
  backend:
    volumes:
      - ../django.secrets:/DJANGO_SECRETS
      - ../backend:/app
  frontend:
    volumes:
      - ../frontend:/app
      - ../social-provider.secrets:/SOCIAL_PROVIDER_SECRETS
      - frontend_node_modules:/app/node_modules
  celery_worker:
    volumes:
      - ../django.secrets:/DJANGO_SECRETS
      - ../backend:/app

volumes:
  frontend_node_modules:
