version: "3.7"
services:
  backend:
    depends_on:
      - postgres
      - redis
  frontend:
    depends_on:
      - backend
  celery_worker:
    depends_on:
      - postgres
      - redis
      - backend
